### ISSUE TITLE
Cannot install GotoEditor 1.3.4 

### ISSUE THREAD

**Issue by wow-meow-ai** [emacs-java/eclipse_goto_editor#1]
Dear authors and maintainers, 

I could not install GotoEditor 1.3.4 plugin in Eclipse Neon 4.6. However this plugin works in Eclipse Mars 4.5.

I've tried the following:
1. Eclipse Market 
2. "help -> Install New Software" manually type in the update site: [ GotoEditor ](http://emacs-java.github.io/eclipse_goto_editor/update-site)

Error message: 

> Cannot complete the install because one or more required items could not be found.
>   Software being installed: org.jf.gotoeditor.feature 1.3.4 (org.jf.gotoeditor.feature.feature.group 1.3.4)
>   Missing requirement: Goto Editor 1.3.4 (org.jf.gotoeditor 1.3.4) requires 'bundle org.eclipse.core.runtime.compatibility 0.0.0' but it could not be found
>   Cannot satisfy dependency:
>     From: org.jf.gotoeditor.feature 1.3.4 (org.jf.gotoeditor.feature.feature.group 1.3.4)
>     To: org.jf.gotoeditor [1.3.4]
1. Download [ org.jf.gotoeditor_1.3.4.jar file ](https://github.com/emacs-java/eclipse_goto_editor/raw/master/org.jf.gotoeditor.site/plugins/org.jf.gotoeditor_1.3.4.jar) directly, put it in the "dropins" folder and restart the IDE.

No error message.

Thank you and Best regards,
Honig

**Comment by gsnerf** [comment]
@gundamlh: with direct download there is no error, but no plugin execution either. I can see neither the options nor the context menu entry.

**Comment by jixiuf** [comment]
try again for 1.3.5
should be fixed

**Comment by gsnerf** [comment]
Confirmed, works as expected now. Thanks!
